app/forms/appointment_types.py
from wtforms import (DecimalField, HiddenField, IntegerField, SelectField,
                     SubmitField)
from wtforms.validators import DataRequired, NumberRange

from app.constants import CURRENCIES
from app.forms import CustomFlaskForm, CustomSelectField
from app.models.appointment_type import AppointmentType
from app.models.enums import TherapyMode, TherapyType
from app.utils.validators import MinimumStripeFee, TherapistLocationRequired


class AppointmentTypeForm(CustomFlaskForm):
    therapy_type = CustomSelectField(
        "Type",
        choices=[("", "Select type")]
        + [(choice.name, choice.value) for choice in TherapyType],
        default="",
        validators=[DataRequired()],
    )
    therapy_mode = CustomSelectField(
        "Mode",
        choices=[("", "Select mode")]
        + [(choice.name, choice.value) for choice in TherapyMode],
        default="",
        validators=[DataRequired(), TherapistLocationRequired()],
    )
    duration = IntegerField(
        "Duration (minutes)",
        validators=[DataRequired(), NumberRange(min=1)],
    )
    fee_amount = DecimalField(
        "Fee",
        validators=[DataRequired(), NumberRange(min=0.01), MinimumStripeFee()],
    )
    fee_currency = SelectField(
        "Currency",
        choices=[("", "Select currency")]
        + [(currency, currency) for currency in CURRENCIES],
        validators=[DataRequired()],
    )
    appointment_type: AppointmentType = None

    def __init__(self, *args, **kwargs):
        super(AppointmentTypeForm, self).__init__(*args, **kwargs)
        appointment_type = kwargs.get("obj")
        if appointment_type:
            self.appointment_type = appointment_type
            self.therapy_type.preselect_choices(appointment_type.therapy_type)
            self.therapy_mode.preselect_choices(appointment_type.therapy_mode)
        return


class DeleteAppointmentTypeForm(CustomFlaskForm):
    appointment_type_id = HiddenField(
        "Appointment type ID", validators=[DataRequired()]
    )
    submit = SubmitField("Delete")

app/views/appointment_types.py
from flask import Blueprint, abort, flash, jsonify, url_for
from flask_login import current_user, login_required

from app import db
from app.forms.appointment_types import (AppointmentTypeForm,
                                         DeleteAppointmentTypeForm)
from app.models.appointment_type import AppointmentType
from app.utils.decorators import therapist_required

bp = Blueprint("appointment_types", __name__, url_prefix="/appointment-types")


@bp.route("/create", methods=["POST"])
@login_required
@therapist_required
def create():
    form = AppointmentTypeForm(prefix="new")

    # Invalid form submission - return errors
    if not form.validate_on_submit():
        return jsonify({"success": False, "errors": form.errors, "form_prefix": "new"})

    # Create a new appointment type
    new_appointment_type = AppointmentType(
        therapist_id=current_user.therapist.id,
        therapy_type=form.therapy_type.data,
        therapy_mode=form.therapy_mode.data,
        duration=form.duration.data,
        fee_amount=form.fee_amount.data,
        fee_currency=form.fee_currency.data,
        active=True,
    )
    db.session.add(new_appointment_type)
    db.session.commit()

    flash("Appointment type created", "success")
    return jsonify(
        {
            "success": True,
            "url": url_for(
                "therapists.therapist",
                therapist_id=current_user.therapist.id,
                section="appointment-types",
            ),
        }
    )


@bp.route("/update/<int:appointment_type_id>", methods=["POST"])
@login_required
@therapist_required
def update(appointment_type_id):
    # Find the appointment type by ID
    appointment_type = db.get_or_404(AppointmentType, appointment_type_id)

    # Appointment type does not belong to this therapist
    if appointment_type.therapist.user.id != current_user.id:
        abort(403)

    form = AppointmentTypeForm(prefix=str(appointment_type_id))

    # Invalid form submission - return errors
    if not form.validate_on_submit():
        return jsonify(
            {
                "success": False,
                "errors": form.errors,
                "form_prefix": appointment_type_id,
            }
        )

    # Soft delete - mark existing appointment type as inactive for integrity
    appointment_type.active = False

    # Create a new appointment type
    new_appointment_type = AppointmentType(
        therapist_id=current_user.therapist.id,
        therapy_type=form.therapy_type.data,
        therapy_mode=form.therapy_mode.data,
        duration=form.duration.data,
        fee_amount=form.fee_amount.data,
        fee_currency=form.fee_currency.data,
        active=True,
    )
    db.session.add(new_appointment_type)
    db.session.commit()

    flash("Appointment type updated", "success")
    return jsonify(
        {
            "success": True,
            "url": url_for(
                "therapists.therapist",
                therapist_id=current_user.therapist.id,
                section="appointment-types",
            ),
        }
    )


@bp.route("/delete", methods=["POST"])
@login_required
@therapist_required
def delete():
    # Retrieve appointment type ID from hidden field in form
    form = DeleteAppointmentTypeForm()
    appointment_type_id = form.appointment_type_id.data

    # Fetch appointment with this ID
    appointment_type = db.session.execute(
        db.select(AppointmentType).filter_by(
            id=appointment_type_id, therapist_id=current_user.therapist.id
        )
    ).scalar_one()

    # Appointment type does not belong to this therapist
    if appointment_type.therapist.user.id != current_user.id:
        abort(403)

    # Soft delete appointment to maintain historical integrity
    appointment_type.active = False
    db.session.commit()

    # Redirect to appointment types page
    flash("Appointment type deleted", "warning")
    return jsonify(
        {
            "success": True,
            "url": url_for(
                "therapists.therapist",
                therapist_id=current_user.therapist.id,
                section="appointment-types",
            ),
        }
    )

app/views/appointments.py
from datetime import datetime

from flask import (Blueprint, Response, abort, flash, jsonify, redirect,
                   render_template, render_template_string, request, session,
                   url_for)
from flask_login import current_user, login_required
from sqlalchemy import func, or_

from app import db
from app.forms.appointments import (AppointmentNotesForm, BookAppointmentForm,
                                    FilterAppointmentsForm,
                                    TherapyExerciseForm, UpdateAppointmentForm)
from app.models.appointment import Appointment
from app.models.appointment_notes import AppointmentNotes
from app.models.client import Client
from app.models.enums import (AppointmentStatus, EmailSubject, PaymentStatus,
                              TherapyMode, TherapyType, UserRole)
from app.models.intervention import Intervention
from app.models.issue import Issue
from app.models.therapist import Therapist
from app.models.therapy_exercise import TherapyExercise
from app.models.user import User
from app.utils.decorators import client_required, therapist_required
from app.utils.formatters import convert_str_to_date, get_flashed_message_html
from app.utils.mail import send_appointment_update_email
from app.views.stripe import create_checkout_session

bp = Blueprint("appointments", __name__, url_prefix="/appointments")
FILTERS_SESSION_KEY = "appointment_filters"


@bp.route("/", methods=["GET"])
@login_required
def index():
    # Dynamically choose the criteria to filter appointments depending on user's role
    if current_user.role == UserRole.THERAPIST:
        filter_criteria = Appointment.therapist_id == current_user.therapist.id
    elif current_user.role == UserRole.CLIENT:
        filter_criteria = Appointment.client_id == current_user.client.id

    # Fetch all of the the current user's appointments ordered by the most recent
    appointments = (
        db.session.execute(
            db.select(Appointment)
            .filter(filter_criteria)
            .order_by(Appointment.time.desc())
        )
        .scalars()
        .all()
    )

    # Convert dates stored as str in session to initialise filter form
    filters = session.get(FILTERS_SESSION_KEY, {})
    if "start_date" in filters and filters["start_date"]:
        filters["start_date"] = convert_str_to_date(filters["start_date"])
    if "end_date" in filters and filters["end_date"]:
        filters["end_date"] = convert_str_to_date(filters["end_date"])

    # Initialise filter form with fields prepopulated from session
    filter_form = FilterAppointmentsForm(
        id="filter-appointments",
        endpoint=url_for("appointments.filter"),
        data=filters,
    )

    # Render the page with the appointment forms
    return render_template(
        "appointments.html",
        active_page="appointments",
        appointments=appointments,
        filter_form=filter_form,
    )


@bp.route("/<int:appointment_id>", methods=["GET"])
@login_required
def appointment(appointment_id: int) -> Response:
    # Fetch appointment with this ID
    appointment = db.get_or_404(Appointment, appointment_id)

    # Current user is not in this appointment
    if appointment.this_user.id != current_user.id:
        abort(403)

    # Initialise form to update appointment, passing role to distinguish allowed actions
    update_form = UpdateAppointmentForm(
        id="update-appointment-form",
        endpoint=url_for(
            "appointments.update",
            appointment_id=appointment_id,
        ),
        role=current_user.role,
    )

    # Create form to set and update a therapy exercise
    exercise_form = TherapyExerciseForm(
        id="therapy-exercise-form",
        endpoint=url_for("appointments.exercise", appointment_id=appointment_id),
        role=current_user.role,
        obj=appointment.exercise,
    )

    # Do not give other users access to appointment notes
    notes_form = None

    # Create appointment notes form for therapist only
    if current_user.role == UserRole.THERAPIST:
        notes_form = AppointmentNotesForm(
            id="appointment-notes-form",
            endpoint=url_for("appointments.notes", appointment_id=appointment_id),
            obj=appointment.notes,
        )

    # Render the page with the appointment details and forms
    return render_template(
        "appointment.html",
        active_page="appointments",
        appointment=appointment,
        update_form=update_form,
        notes_form=notes_form,
        exercise_form=exercise_form,
    )


@bp.route("/create/<int:therapist_id>", methods=["POST"])
@login_required
@client_required
def create(therapist_id: int) -> Response:
    # Ensure client has completed onboarding
    if not current_user.onboarding_complete:
        flash(
            "Please complete your onboarding before booking an appointment", "warning"
        )
        return redirect(url_for("profile.profile", user_id=current_user.id))

    # Fetch therapist with this ID to initialise form correctly
    therapist = db.get_or_404(Therapist, therapist_id)

    form = BookAppointmentForm(obj=therapist)

    # Invalid form submission - return errors
    if not form.validate_on_submit():
        return jsonify({"success": False, "errors": form.errors})

    # Add new appointment with pending payment in database
    appointment = Appointment(
        therapist_id=therapist_id,
        client_id=current_user.client.id,
        appointment_type_id=form.appointment_type.data,
        time=datetime.combine(form.date.data, form.time.data),
        appointment_status=AppointmentStatus.SCHEDULED,
        payment_status=PaymentStatus.PENDING,
    )
    db.session.add(appointment)
    db.session.commit()

    # Redirect the client to Stripe Checkout
    if not therapist.stripe_account_id:
        return jsonify(
            {
                "success": True,
                "url": url_for(
                    "appointments.appointment", appointment_id=appointment.id
                ),
                "flashed_message_html": get_flashed_message_html(
                    "Appointment scheduled, awaiting payment and confirmation",
                    "info",
                ),
            }
        )

    checkout_session_url = create_checkout_session(appointment)

    if not checkout_session_url:
        return jsonify(
            {
                "success": False,
                "flashed_message_html": get_flashed_message_html(
                    "Failed to initiate payment via Stripe, please contact therapist",
                    "error",
                ),
            }
        )
    else:
        return jsonify(
            {
                "success": False,
                "url": checkout_session_url,
            }
        )


@bp.route("/update/<int:appointment_id>", methods=["POST"])
@login_required
def update(appointment_id: int) -> Response:
    # Fetch appointment with this ID
    appointment = db.get_or_404(Appointment, appointment_id)

    # Current user is not in this appointment
    if appointment.this_user.id != current_user.id:
        abort(403)

    form = UpdateAppointmentForm(role=current_user.role)

    # Invalid form submission - return errors
    if not form.validate_on_submit():
        return jsonify({"success": False, "errors": form.errors})

    new_status = AppointmentStatus[form.action.data]

    # Do nothing if status has not changed
    if appointment.appointment_status == new_status:
        return jsonify({"success": True})

    # Handle missing date and time fields for rescheduled
    if new_status == AppointmentStatus.RESCHEDULED:
        datetime_errors = {}
        if form.new_date.data is None:
            datetime_errors["new_date"] = ["New date is required."]
        if form.new_time.data is None:
            datetime_errors["new_time"] = ["New time is required."]

        if datetime_errors:
            return jsonify({"success": False, "errors": datetime_errors})

    flashed_message_text = None
    flashed_message_category = None

    # Handle actions differently depending on role of current user
    if current_user.role == UserRole.THERAPIST:
        # CONFIRMED - notify client
        if new_status == AppointmentStatus.CONFIRMED:
            send_appointment_update_email(
                appointment=appointment,
                recipient=appointment.client.user,
                subject=EmailSubject.APPOINTMENT_CONFIRMED_CLIENT,
            )
            flashed_message_text = "Appointment confirmed, client notified"
            flashed_message_category = "success"

        # RESCHEDULED - notify client and update appointment time
        elif new_status == AppointmentStatus.RESCHEDULED:
            send_appointment_update_email(
                appointment=appointment,
                recipient=appointment.client.user,
                subject=EmailSubject.APPOINTMENT_RESCHEDULED,
            )
            appointment.time = datetime.combine(form.new_date.data, form.new_time.data)
            flashed_message_text = "Appointment rescheduled, client notified"
            flashed_message_category = "success"

        # COMPLETED - do nothing
        elif new_status == AppointmentStatus.COMPLETED:
            flashed_message_text = "Appointment recorded as completed"
            flashed_message_category = "success"

        # CANCELLED - notify client
        elif new_status == AppointmentStatus.CANCELLED:
            send_appointment_update_email(
                appointment=appointment,
                recipient=appointment.client.user,
                subject=EmailSubject.APPOINTMENT_CANCELLED,
            )
            flashed_message_text = "Appointment cancelled, client notified"
            flashed_message_category = "warning"

        # NO SHOW - notify client
        elif new_status == AppointmentStatus.NO_SHOW:
            send_appointment_update_email(
                appointment=appointment,

app/views/profile.py
from flask import Blueprint, Response, redirect, request, url_for
from flask_login import current_user, login_required

from app import db
from app.models.enums import UserRole
from app.models.user import User

bp = Blueprint("profile", __name__, url_prefix="/profile")


@bp.route("/", methods=["GET"])
@login_required
def index() -> Response:
    default_section = request.args.get("section")
    return redirect(
        url_for("profile.profile", user_id=current_user.id, section=default_section)
    )


@bp.route("/<int:user_id>", methods=["GET"])
@login_required
def profile(user_id: int) -> Response:
    # Fetch user with this id
    user = db.get_or_404(User, user_id)

    default_section = request.args.get("section")

    # Redirect user to their role-specific profile page
    if user.role == UserRole.THERAPIST:
        if user.therapist:
            url = url_for(
                "therapists.therapist",
                therapist_id=user.therapist.id,
                section=default_section,
            )
        else:
            url = url_for("therapists.new_therapist", section=default_section)

    elif user.role == UserRole.CLIENT:
        if user.client:
            url = url_for(
                "clients.client",
                client_id=user.client.id,
                section=default_section,
            )
        else:
            url = url_for("clients.new_client", section=default_section)

    else:
        print(f"Unhandled user role: {current_user.role}")
        url = url_for("main.index")

    return redirect(url)

app/templates/_navbar.html
<nav class="navbar navbar-expand-md">
    <div class="container-fluid">
        
        <!-- Brand -->
        <a class="navbar-brand" href="/">
            <img src="{{ url_for('static', filename='img/logos/logo.png') }}" alt="Logo" height="24" class="d-inline-block align-text-top me-1">
            mindli
        </a>
      
        <!-- Toggler -->
        <button class="navbar-toggler nav-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarBody" aria-controls="navbarBody" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fa-solid fa-bars"></i>
        </button>
    
        <!-- Body -->
        <div class="collapse navbar-collapse" id="navbarBody">
            
            {% if not current_user.is_authenticated %}
                <!-- Links -->
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class='nav-item'>
                        <a class='nav-link' href='/' data-page="#">About</a>
                    </li>
                    <li class='nav-item'>
                        <a class='nav-link' href='/therapists' data-page="therapists">Therapists</a>
                    </li>
                    <li class='nav-item'>
                        <a class='nav-link' href='/contact' data-page="#">Contact Us</a>
                    </li>
                </ul>
            {% endif %}

            <!-- Buttons -->
            <div class="d-flex ms-auto">
                {% if not current_user.is_authenticated %}
                    <a class='nav-link btn btn-outline-secondary h-auto me-2' href='/login' data-page="login">Sign In</a>
                    <a class='nav-link btn btn-primary h-auto' href='/register' data-page="register">Get Started</a>
                {% else %}
                    <a class='nav-link btn btn-outline-secondary h-auto' href='/logout'>Sign Out</a>
                {% endif %}
            </div>

        </div>
    </div>
</nav>

app/templates/_sidebar.html
<div class="sidebar">
    
  <!-- Header -->
    <div class="sidebar-header">
        
      <!-- Brand -->
      <a class="navbar-brand" href="/">
          <img src="{{ url_for('static', filename='img/logos/logo.png') }}" alt="Logo" height="24" class="d-inline-block align-text-top mx-1">
          mindli
      </a>

      <!-- Toggler -->
      <button class="btn navbar-toggler h-auto" type="button" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-custom-class="my-tooltip" data-bs-title="Expand">
        <i class="fa-solid fa-bars"></i>
      </button>
    </div>

    <hr>

    <!-- Body -->
    <ul class="nav flex-column">
      <li class="nav-item">
        <a class="nav-link" href="/" data-page="home" 
           data-bs-toggle="tooltip" data-bs-placement="right" data-bs-custom-class="my-tooltip" data-bs-title="Home">
          <i class="fa-solid fa-house"></i>
          <span>Home</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('profile.index') }}" data-page="profile"
           data-bs-toggle="tooltip" data-bs-placement="right" data-bs-custom-class="my-tooltip" data-bs-title="Profile">
          <i class="fas fa-user"></i>
          <span>Profile</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('messages.index') }}" data-page="messages" 
           data-bs-toggle="tooltip" data-bs-placement="right" data-bs-custom-class="my-tooltip" data-bs-title="Messages">
          <i class="fas fa-comments"></i>
          <span>Messages</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('appointments.index') }}" data-page="appointments"
           data-bs-toggle="tooltip" data-bs-placement="right" data-bs-custom-class="my-tooltip" data-bs-title="Appointments">
          <i class="fas fa-calendar"></i>
          <span>Appointments</span>
        </a>
      </li>
      {% if current_user.role == UserRole.THERAPIST %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('clients.index') }}" data-page="clients"
             data-bs-toggle="tooltip" data-bs-placement="right" data-bs-custom-class="my-tooltip" data-bs-title="Clients">
            <i class="fas fa-users"></i>
            <span>Clients</span>
          </a>
        </li>
      {% endif %}
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('therapists.index') }}" data-page="therapists"
           data-bs-toggle="tooltip" data-bs-placement="right" data-bs-custom-class="my-tooltip" data-bs-title="Therapists">
          <i class="fas fa-user-md"></i>
          <span>Therapists</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/logout" data-page="logout"
           data-bs-toggle="tooltip" data-bs-placement="right" data-bs-custom-class="my-tooltip" data-bs-title="Sign Out">
          <i class="fas fa-sign-out-alt"></i>
          <span>Sign Out</span>
        </a>
      </li>
    </ul>
  </div>

app/templates/clients.html
{% extends 'layout.html' %}

{% block title %}
    Clients
{% endblock %}

{% block content %}

    <div class='container'>
        
        <div class='row mb-3 g-4'>
            <div class='col-lg-12'>
                <h4>Client Directory</h4>
            </div>
        </div>
        
        <div class="row g-4 mb-4">
            <div class='col-lg-12'>
                <div class='my-card'>
                    
                    <h5 class="row mb-3">
                        <div class="col-12">
                            Client Finder
                        </div>
                    </h5>

                    <form id="{{ filter_form.id }}" action="{{ filter_form.endpoint }}" novalidate>
                                    
                        {{ filter_form.csrf_token }}

                        <div class="accordion accordion-flush" id="filterAccordion">

                            <!-- Personal details -->
                            <div class="accordion-item row">
                                <div class="col-12">
                        
                                    <div class="accordion-header row">
                                        <div class="col-12">
                                            <h6 class="mb-0">
                                                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#personalDetailsCollapse" aria-expanded="false" aria-controls="personalDetailsCollapse">
                                                By personal details
                                                </button>
                                            </h6>
                                        </div>
                                    </div>
        
                                    <div id="personalDetailsCollapse" class="accordion-collapse collapse text-s">

                                        <div class="accordion-body">
                                        
                                            <div class="row g-2 mb-2">
                                                <div class="col-lg-auto">
                                                    <div class="form-floating">
                                                        {{ filter_form.name(class_='form-control', placeholder=filter_form.name.label.text) }}
                                                        {{ filter_form.name.label }}
                                                    </div>
                                                </div>
            
                                                <div class="col-lg-auto">
                                                    <div class="form-floating">
                                                        {{ filter_form.gender(class_='form-control', placeholder=filter_form.gender.label.text) }}
                                                        {{ filter_form.gender.label }}
                                                    </div>
                                                </div>
                
                                                <div class="col-lg-auto">
                                                    <div class='form-floating'>
                                                        {{ filter_form.min_age(class_='form-control', placeholder=filter_form.min_age.label.text) }}
                                                        {{ filter_form.min_age.label }}
                                                    </div>
                                                </div>

                                                <div class="col-lg-auto">
                                                    <div class='form-floating'>
                                                        {{ filter_form.max_age(class_='form-control', placeholder=filter_form.max_age.label.text) }}
                                                        {{ filter_form.max_age.label }}
                                                    </div>
                                                </div>

                                                <div class="col-lg-auto">
                                                    <div class='form-floating'>
                                                        {{ filter_form.occupation(class_='form-control', placeholder=filter_form.occupation.label.text) }}
                                                        {{ filter_form.occupation.label }}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <!-- Background -->
                            <div class="accordion-item row">
                                <div class="col-12">
                        
                                    <div class="accordion-header row">
                                        <div class="col-12">
                                            <h6 class="mb-0">
                                                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#backgroundCollapse" aria-expanded="false" aria-controls="backgroundCollapse">
                                                By background
                                                </button>
                                            </h6>
                                        </div>
                                    </div>
        
                                    <div id="backgroundCollapse" class="accordion-collapse collapse text-s">

                                        <div class="accordion-body">
                                        
                                            <div class="row g-2 mb-2">

                                                <div class="col-lg-auto">
                                                    <div class="form-floating">
                                                        {{ filter_form.issues(class_='form-control', placeholder=filter_form.issues.label.text) }}
                                                        {{ filter_form.issues.label }}
                                                    </div>
                                                </div>
            
                                                <div class="col-lg-auto">
                                                    <div class="form-floating">
                                                        {{ filter_form.referral_source(class_='form-control', placeholder=filter_form.referral_source.label.text) }}
                                                        {{ filter_form.referral_source.label }}
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                                    
                        <div class="row mt-2 g-2">
                            <div class="col-auto">
                                {{ submit_button(filter_form.submit_filter, extra_class='w-auto') }}
                            </div>
                            <div class="col-auto">
                                {{ submit_button(filter_form.submit_reset_filters, class='btn btn-secondary', extra_class='w-auto') }}
                            </div>
                        </div>
                    </form>

                    <div class="row mt-4">
                        <div class="col-auto my-muted" id="filter-count">
                            {{ clients|length if clients else 0}} clients found
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div id="client-cards" class="row g-4">
            {{ client_cards(clients) }}
        </div>

    </div>

{% endblock %}